apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: default
  labels:
    app: redis-cluster
    env: dev
spec:
  ports:
  - name: http
    port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: redis-cluster
